




FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci




COPY . .

RUN npx prisma generate
RUN npm run build






FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules



COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma7.config.ts ./prisma7.config.ts

COPY --from=builder /app/src/generated ./src/generated

EXPOSE 3000



CMD ["node", "dist/main.js"]